# Saʿid – High‑School Bagrut Preparation App

**Author:** Muhammad Badran  
**Platform:** Android Studio
**Backend:** Firebase (Realtime DB, Storage, Firestore, Auth)

---

## 📖 Introduction

_Saʿid_ is a comprehensive mobile platform designed for Israeli high‑school students preparing for the Bagrut exams. It bundles:

- **Exam calendar & reminders** – auto‑imported from MoE CSV → JSON pipeline  
- **Grades calculator** – real‑time tracking of final scores per subject  
- **Bagrut bank** – past exams, official solutions, quizzes  
- **Study materials** – upload/download, admin approval system  
- **Announcements & feedback** – push notifications and two‑way messaging  
- **User authentication** – email/password + Google Sign‑In

---

## ⚙️ Features

1. **User Auth**  
   - Email/password & Google OAuth  
   - Profile editing (picture & username)

2. **Bagrut Subject Selection**  
   - Mandatory subjects with unit‑level radio buttons  
   - Elective majors & “advanced mode” exam ID checklist  

3. **Exam Calendar**  
   - Firebase Realtime‐DB import of official MoE timetable  
   - Local notifications respecting extra‑time entitlement  

4. **Grades Calculator**  
   - Flexible weighting per component  
   - Instant updates & progress tracking  

5. **Materials & Exams Bank**  
   - Browse past exams & solutions  
   - Upload new resources for review  

6. **Announcements & Feedback**  
   - Admin‐driven notices  
   - In‑app feedback system  

7. **Settings & Preferences**  
   - Theme, notification toggles, extra‑time settings  

---

## 🚀 Getting Started

### Prerequisites

- Android Studio Bumblebee or later  
- Kotlin 1.6+  
- Firebase project with:  
  - Realtime Database  
  - Cloud Firestore  
  - Storage  
  - Authentication enabled  

### Installation

1. **Clone the repo**  
   ```bash
   git clone https://github.com/your‑username/sa3id‑app.git
   cd sa3id‑app
````

2. **Configure Firebase**

   * Place your `google-services.json` in `app/`.
   * Update the Realtime DB URL in `Constants.java`.

3. **Build & Run**

   * Sync Gradle, then run on emulator or device.

---

## 🏗️ Architecture & UML

The app follows an MVVM‑inspired structure with:

* **Activities/Fragments** for UI
* **Managers** (e.g., `ExamManager`) for Firebase logic
* **Models** for data classes

### UML Class Diagram

> *(Let me know when you’re ready and send the UML image, and I’ll insert it here.)*

```markdown
![UML Diagram](docs/uml.png)
```

---

## 🖼️ Screenshots

> *(Provide screenshots for key screens: Sign‑In, Main Dashboard, Exams List, Grades Calculator.)*

```markdown
![Sign‑In Screen](docs/screens/signin.png)
![Dashboard](docs/screens/dashboard.png)
![Exam Calendar](docs/screens/calendar.png)
```

---

## 🤝 Contributing

1. Fork the repo
2. Create a feature branch (`git checkout -b feature/XYZ`)
3. Commit your changes (`git commit -m "Add XYZ"`)
4. Push to your branch (`git push origin feature/XYZ`)
5. Open a Pull Request

Please follow the existing code style: minimal lowercase comments, clear method names, and no autogenerated AI code blocks.

---

## 📄 License

Distributed under the MIT License. See [LICENSE](LICENSE) for more details.


